import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/notification_model.dart';

class SupabaseNotificationService {
  static final SupabaseClient _client = Supabase.instance.client;

  // Get all notifications - simplified version
  static Future<List<Notification>> getNotifications({
    int page = 1,
    int limit = 20,
  }) async {
    try {
      final response = await _client
          .from('notifications')
          .select('*')
          .order('created_at', ascending: false)
          .range((page - 1) * limit, (page * limit) - 1);

      return (response as List).map((e) => Notification.fromJson(e)).toList();
    } catch (e) {
      throw Exception('Failed to fetch notifications: $e');
    }
  }

  // Get notification by ID
  static Future<Notification?> getNotificationById(String id) async {
    try {
      final response = await _client
          .from('notifications')
          .select('*')
          .eq('id', id)
          .maybeSingle();

      if (response == null) return null;
      return Notification.fromJson(response);
    } catch (e) {
      throw Exception('Failed to fetch notification: $e');
    }
  }

  // Create new notification
  static Future<Notification> createNotification(
    Notification notification,
  ) async {
    try {
      final response = await _client
          .from('notifications')
          .insert(notification.toJson())
          .select()
          .single();

      return Notification.fromJson(response);
    } catch (e) {
      throw Exception('Failed to create notification: $e');
    }
  }

  // Delete notification
  static Future<void> deleteNotification(String id) async {
    try {
      await _client.from('notifications').delete().eq('id', id);
    } catch (e) {
      throw Exception('Failed to delete notification: $e');
    }
  }

  // Mark notification as read
  static Future<Notification> markAsRead(String notificationId) async {
    try {
      final response = await _client
          .from('notifications')
          .update({
            'is_read': true,
            'status': 'read',
            'read_at': DateTime.now().toIso8601String(),
          })
          .eq('id', notificationId)
          .select()
          .single();

      return Notification.fromJson(response);
    } catch (e) {
      throw Exception('Failed to mark notification as read: $e');
    }
  }

  // Mark notification as unread
  static Future<Notification> markAsUnread(String notificationId) async {
    try {
      final response = await _client
          .from('notifications')
          .update({'is_read': false, 'status': 'unread', 'read_at': null})
          .eq('id', notificationId)
          .select()
          .single();

      return Notification.fromJson(response);
    } catch (e) {
      throw Exception('Failed to mark notification as unread: $e');
    }
  }

  // Mark all notifications as read
  static Future<void> markAllAsRead() async {
    try {
      await _client.from('notifications').update({
        'is_read': true,
        'status': 'read',
        'read_at': DateTime.now().toIso8601String(),
      });
    } catch (e) {
      throw Exception('Failed to mark all notifications as read: $e');
    }
  }

  // Get unread notifications count
  static Future<int> getUnreadCount() async {
    try {
      final response = await _client
          .from('notifications')
          .select('id')
          .eq('is_read', false);

      return (response as List).length;
    } catch (e) {
      throw Exception('Failed to get unread count: $e');
    }
  }

  // Create notification for lead assignment
  static Future<Notification> createLeadAssignmentNotification({
    required String leadId,
    required String leadTitle,
    required String assignedToUserId,
    required String assignedToUserName,
    required String assignedByName,
  }) async {
    final notification = Notification(
      id: '', // Will be generated by database
      title: 'New Lead Assigned',
      message: 'You have been assigned lead: $leadTitle',
      type: NotificationType.lead,
      priority: NotificationPriority.medium,
      status: NotificationStatus.unread,
      userId: assignedToUserId,
      relatedId: leadId,
      relatedType: 'lead',
      actionUrl: '/leads/$leadId',
      data: {
        'lead_id': leadId,
        'lead_title': leadTitle,
        'assigned_by': assignedByName,
      },
      createdAt: DateTime.now(),
    );

    return await createNotification(notification);
  }

  // Create notification for site visit scheduled
  static Future<Notification> createSiteVisitNotification({
    required String siteVisitId,
    required String leadId,
    required String customerName,
    required String projectName,
    required DateTime visitDateTime,
    required String userId,
  }) async {
    final notification = Notification(
      id: '', // Will be generated by database
      title: 'Site Visit Scheduled',
      message:
          'Site visit with $customerName for $projectName at ${visitDateTime.toString()}',
      type: NotificationType.siteVisit,
      priority: NotificationPriority.high,
      status: NotificationStatus.unread,
      userId: userId,
      relatedId: siteVisitId,
      relatedType: 'site_visit',
      actionUrl: '/site-visits/$siteVisitId',
      data: {
        'site_visit_id': siteVisitId,
        'lead_id': leadId,
        'customer_name': customerName,
        'project_name': projectName,
        'visit_date_time': visitDateTime.toIso8601String(),
      },
      createdAt: DateTime.now(),
    );

    return await createNotification(notification);
  }

  // Create notification for booking confirmed
  static Future<Notification> createBookingNotification({
    required String bookingId,
    required String leadId,
    required String customerName,
    required String projectName,
    required String userId,
  }) async {
    final notification = Notification(
      id: '', // Will be generated by database
      title: 'Booking Confirmed',
      message: 'Booking for $customerName in $projectName has been confirmed',
      type: NotificationType.booking,
      priority: NotificationPriority.high,
      status: NotificationStatus.unread,
      userId: userId,
      relatedId: bookingId,
      relatedType: 'booking',
      actionUrl: '/bookings/$bookingId',
      data: {
        'booking_id': bookingId,
        'lead_id': leadId,
        'customer_name': customerName,
        'project_name': projectName,
      },
      createdAt: DateTime.now(),
    );

    return await createNotification(notification);
  }

  // Create notification for task assigned
  static Future<Notification> createTaskNotification({
    required String taskId,
    required String taskTitle,
    required String assignedToUserId,
    required String assignedByName,
  }) async {
    final notification = Notification(
      id: '', // Will be generated by database
      title: 'New Task Assigned',
      message: 'You have been assigned task: $taskTitle',
      type: NotificationType.system,
      priority: NotificationPriority.medium,
      status: NotificationStatus.unread,
      userId: assignedToUserId,
      relatedId: taskId,
      relatedType: 'task',
      actionUrl: '/tasks/$taskId',
      data: {
        'task_id': taskId,
        'task_title': taskTitle,
        'assigned_by': assignedByName,
      },
      createdAt: DateTime.now(),
    );

    return await createNotification(notification);
  }
}
